theme: jekyll-theme-minimal
title: Oscar Contreras
show_downloads: false
logo: https://media-exp3.licdn.com/dms/image/C4E03AQHZoainq-zecA/profile-displayphoto-shrink_800_800/0/1556659863972?e=1630540800&v=beta&t=g-YJToIMd-bZL6PBKg2ZAraReYQyTB5YdTUHaGp929c
